Add JWT token and guard against unauthenticated requests
theNEXlevel/metro-atlanta-saves pull request #23
Opened 2024-02-18 18:27 UTC by taichatha

2024-02-18 18:37 UTC, theNEXlevel requested changes

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/auth/auth.service.ts
> +    return this.signToken(parseInt(user.id), user.email);
the user.id is a string so may need to update the types.

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/auth/auth.service.ts
> +      expiresIn: '15m',
I would set the expire token to be at least a week, I personally prefer for a project like this setting it to a year.

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/auth/decorator/get-user.decorator.ts
> +export const GetUser = createParamDecorator(
For the guards we'll need to setup group permissions which is a another layer of complexity that we don't need right now.

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/auth/strategy/jwt.strategy.ts
> +    console.log(payload);
remove console logs

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/auth/strategy/jwt.strategy.ts
> +    sub: number;
sub likely needs to be a string because our id's are strings

2024-02-18 18:37 UTC, theNEXlevel commented on apps/backend/src/app/users/user.controller.ts
> +  getMe(@GetUser() user: User,
I don't think we'll need an endpoint like this at least not right now. When the signin / signup request completes we should return the entire user object with that request.

2024-02-18 18:46 UTC, theNEXlevel commented on apps/backend/src/app/auth/auth.service.ts
> +  constructor(
I forgot to mention but it's best to run the generators when generating the services / controllers so we get the spec files with them. Unit testing is something that I want to make sure we show good coverage for this project at least - I think it will help with our grade.

2024-02-19 09:48 UTC, taichatha commented on apps/backend/src/app/auth/auth.service.ts
> +      expiresIn: '15m',
I think we can set it as a a year.

2024-02-19 09:51 UTC, taichatha commented on apps/backend/src/app/auth/auth.service.ts
> +  constructor(
`prisma-generate`? Which generate function?

2024-02-19 10:00 UTC, taichatha commented on apps/backend/src/app/auth/auth.service.ts
> +  constructor(
I manually added the spec files for now. But I will use generators in the future.

2024-02-19 10:00 UTC, taichatha commented on apps/backend/src/app/auth/strategy/jwt.strategy.ts
> +    sub: number;
done

2024-02-19 10:00 UTC, taichatha commented on apps/backend/src/app/auth/strategy/jwt.strategy.ts
> +    console.log(payload);
Done

2024-02-19 10:01 UTC, taichatha commented on apps/backend/src/app/users/user.controller.ts
> +  getMe(@GetUser() user: User,
I am going to remove the Users directory for now since it doesn't really do anything useful for us now.

2024-02-19 10:01 UTC, taichatha commented on apps/backend/src/app/auth/auth.service.ts
> +    return this.signToken(parseInt(user.id), user.email);
Done

2024-02-19 10:02 UTC, taichatha commented on apps/backend/src/app/auth/decorator/get-user.decorator.ts
> +export const GetUser = createParamDecorator(
I am going to leave these here for now. But I am not using these anywhere now since I removed the User directory.

2024-02-19 18:51 UTC, theNEXlevel approved these changes

2024-02-19 18:52 UTC, merged