create registration page
theNEXlevel/metro-atlanta-saves pull request #27
Opened 2024-02-19 11:45 UTC by taichatha

## Init State
<img width="890" alt="image" src="https://github.com/theNEXlevel/metro-atlanta-saves/assets/8629842/06a01c99-b3c5-4190-a6c9-d1a4c5a2c121">

## Validation Checking:
<img width="394" alt="image" src="https://github.com/theNEXlevel/metro-atlanta-saves/assets/8629842/d37d130f-b2b2-4b82-9338-842dc8150da6">

### password min length
<img width="485" alt="image" src="https://github.com/theNEXlevel/metro-atlanta-saves/assets/8629842/ff2d0aca-dfde-48a7-9120-37d13aff1588">

## Valid State
<img width="381" alt="image" src="https://github.com/theNEXlevel/metro-atlanta-saves/assets/8629842/1f86852a-65b5-47f0-86a5-440cd1461ae8">

There is no redirect as of yet. This just sends a post request to the backend and returns the user.

2024-02-19 13:28 UTC, amadhya02 commented
I would suggest to use tailwind as much as we can to keep it in sync with the other file patterns

2024-02-19 16:46 UTC, taichatha commented
> I would suggest to use tailwind as much as we can to keep it in sync with the other file patterns

What would be an example cmd to run with tailwind?

2024-02-20 02:47 UTC, theNEXlevel requested changes

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/app.routes.ts
> +        title: `Register ${TITLE_SUFFIX}`,
please add a description to the seo info. Something basic like `The registration page to sign up for Metro Atlanta Saves!` is fine.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +#register {
we shouldn't use ID's in Angular as you can have multiple of the same components on the page.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +  color: white;
please refrain from using color / background-color directly in styles. This will overwrite dark mode. Instead you'll need to use material components.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +@use '@angular/material' as mat;
I believe this entire file can be deleted in favor of tailwind classes. Also we're using inline styles so if any styles were needed you would create them in the component.ts file directly.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Let's switch this file to using ng-mocks. It's a lot easier to implement the unit test. Take a look at another component spec file for a reference

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +    <div id="register">
The `div#register` element can be completely removed.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +              <input formControlName="firstName"/>
lets use material inputs - https://material.angular.io/components/input/overview

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +    private fb: FormBuilder,
Let's completely remove the constructor and you can use Angular's new `inject` function.

private fb = inject(FormBuilder);
private registrationService = inject(RegistrationService);

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +    if (this.registerForm.valid) {
I prefer at the beginning of the method to check if the form is invalid and if so return. That way we don't have logic inside of an if.

```
if (this.registerForm.invalid) {
  return;
}
```

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +      const registrationData: RegistrationRequest = this.registerForm.value as RegistrationRequest;
You should be able to get around casting if you use `this.registerForm.getRawValue()`.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.ts
> +  registerForm = this.fb.group({
You should use the nonNullable version of the form builder so you get better type safety: `this.fb.nonNullable.group({...})`

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.service.ts
> +export class RegistrationService {
I would rename this to `AuthService` and then set the baseUrl as `/api/auth` - then in the register method you can do `this.http.post<void>(`${this.baseUrl}/signup`, requestData`.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.service.ts
> +  register(requestData: RegistrationRequest): Observable<any> {
Let's go ahead and use void instead of any if the response doesn't have any data right now - if it does have data let's figure out what that type should be.

2024-02-20 02:47 UTC, theNEXlevel commented on apps/frontend/src/app/register/registration-request.model.ts
> +export interface RegistrationRequest {
We should be able to use the same interface on the front-end and back-end using prisma.

2024-02-20 02:50 UTC, theNEXlevel requested changes

2024-02-20 02:50 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +  display: flex;
use `class="flex justify-center"`

https://tailwindcss.com/docs/flex

2024-02-20 02:50 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +  padding: 10px;
Let's use `class="flex flex-col p-2"`

2024-02-20 02:50 UTC, theNEXlevel commented on apps/frontend/src/app/register/register.component.scss
> +@use '@angular/material' as mat;
I left some comments about some common tailwind classes but take a look at the docs: https://tailwindcss.com/docs/flex

2024-02-20 10:18 UTC, taichatha commented on apps/frontend/src/app/app.routes.ts
> +        title: `Register ${TITLE_SUFFIX}`,
Done

2024-02-20 10:39 UTC, taichatha commented on apps/frontend/src/app/register/register.component.scss
> +@use '@angular/material' as mat;
Removing.

2024-02-20 10:53 UTC, taichatha commented on apps/frontend/src/app/register/registration-request.model.ts
> +export interface RegistrationRequest {
How do I do this? Should I use prisma/client?

I did try to directly import this. 
I am getting this error when trying to import the `SignUpDTO` interface. Should I go ahead and add an npm scope?
<img width="842" alt="image" src="https://github.com/theNEXlevel/metro-atlanta-saves/assets/8629842/0d996b4f-ed47-45e1-b546-852db2dd20a1">

2024-02-20 10:55 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +      const registrationData: RegistrationRequest = this.registerForm.value as RegistrationRequest;
Done

2024-02-20 10:56 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +  registerForm = this.fb.group({
Done

2024-02-20 10:57 UTC, taichatha commented on apps/frontend/src/app/register/register.service.ts
> +export class RegistrationService {
Done

2024-02-20 10:57 UTC, taichatha commented on apps/frontend/src/app/register/register.service.ts
> +  register(requestData: RegistrationRequest): Observable<any> {
Done

2024-02-20 11:01 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +    <div id="register">
Removed

2024-02-20 11:02 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +              <input formControlName="firstName"/>
done

2024-02-20 11:03 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +    if (this.registerForm.valid) {
Done

2024-02-20 11:04 UTC, taichatha commented on apps/frontend/src/app/register/register.component.ts
> +    private fb: FormBuilder,
Done

2024-02-20 11:06 UTC, taichatha commented on apps/frontend/src/app/register/register.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
I don't see any examples of using ng-mocks in the other spec files.

2024-02-20 11:07 UTC, taichatha commented on apps/frontend/src/app/register/register.component.scss
> +  color: white;
Using material components, and removed the scss file.

2024-02-21 05:41 UTC, jmclellan-crexi commented on apps/frontend/src/app/register/register.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Did you merge the latest from main? I updated all of the spec files to use ngMocks. Should be an almost copy/paste from another component.

2024-02-21 05:41 UTC, jmclellan-crexi commented on apps/frontend/src/app/register/registration-request.model.ts
> +export interface RegistrationRequest {
We can leave this alone for now - getting the types inferred is somewhat of a pain when handling DTO's.

2024-02-21 05:48 UTC, taichatha commented on apps/frontend/src/app/register/register.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Ah gotcha. I will rebase and check it out.

2024-02-21 06:46 UTC, jmclellan-crexi approved these changes

2024-02-21 06:46 UTC, theNEXlevel approved these changes

2024-02-21 06:48 UTC, merged