TAS-32
theNEXlevel/metro-atlanta-saves pull request #29
Opened 2024-02-20 23:20 UTC by amadhya02

About Us Page

2024-02-20 23:36 UTC, jmclellan-crexi requested changes

2024-02-20 23:36 UTC, jmclellan-crexi commented on apps/frontend/src/app/about-us/about-us.component.ts
> +type TEAM_MEMBER = {
Types should be PascalCase `TeamMember`

2024-02-20 23:36 UTC, jmclellan-crexi commented on apps/frontend/src/app/app.routes.ts
> +        title: `Helping You Save Money ${TITLE_SUFFIX}`,
Can you add a title / description that reflects this page?

2024-02-20 23:36 UTC, jmclellan-crexi commented on apps/frontend/src/app/home/home.component.ts
> +      route: '/about-us',
We should probably have these link to fragment Routes and enable that in the app. This can be a follow up though because it requires some changes to the router setup.

2024-02-21 17:22 UTC, theNEXlevel approved these changes

2024-02-21 17:22 UTC, merged